// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * A UUID is a Universally Unique Identifier as specified in RFC 9562.
 * 
 * UUIDs are comparable, such as with the == operator.
 */
export type UUID = string;
