// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../uuid/models.js";

export interface Todo {
    "id": uuid$0.UUID;
    "description": string;
    "dueAt"?: string;
    "completedAt"?: string;
    "remindMeAt"?: string;
}
