// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../uuid/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddTodo(todo: $models.Todo): $CancellablePromise<void> {
    return $Call.ByID(4097713788, todo);
}

export function DeleteAll(): $CancellablePromise<void> {
    return $Call.ByID(2654288625);
}

export function DeleteTodo(todo: $models.Todo): $CancellablePromise<void> {
    return $Call.ByID(2048827770, todo);
}

export function DeleteTodoById(todoId: uuid$0.UUID): $CancellablePromise<void> {
    return $Call.ByID(351766894, todoId);
}

export function GetActiveTodos(): $CancellablePromise<$models.Todo[] | null> {
    return $Call.ByID(1718883318);
}

export function GetAllTodos(): $CancellablePromise<$models.Todo[] | null> {
    return $Call.ByID(4237896323);
}

export function GetCompletedTodos(): $CancellablePromise<$models.Todo[] | null> {
    return $Call.ByID(1265103409);
}

export function GetTodo(id: uuid$0.UUID): $CancellablePromise<$models.Todo | null> {
    return $Call.ByID(4199289255, id);
}

export function UpdateTodo(todo: $models.Todo): $CancellablePromise<void> {
    return $Call.ByID(2318538620, todo);
}
