// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function HideTodoReminder(): $CancellablePromise<void> {
    return $Call.ByID(2412510537);
}

export function OpenTodosWindow(): $CancellablePromise<void> {
    return $Call.ByID(4116832656);
}

export function ShowTodoReminder(todo: $models.Todo): $CancellablePromise<void> {
    return $Call.ByID(2625931712, todo);
}
